QXlsx/source/xlsxzipreader.cpp
Neither 'Microsoft Office Professional Plus 2019' nor 'LibreOffice Ca…lc 6.3.2.2' write a valid flag for 'isFile'. Therefore we check if no flag is set and handle it as file.
=> Flag "isFile" has not always a valid value

QXlsx/header/xlsxabstractsheet_p.h, QXlsx/header/xlsxglobal.h, QXlsx/header/xlsxworksheet_p.h, QXlsx/source/xlsxcell.cpp, QXlsx/source/xlsxcellreference.cpp, QXlsx/source/xlsxchart.cpp, QXlsx/source/xlsxchartsheet.cpp, QXlsx/source/xlsxcolor.cpp, QXlsx/source/xlsxconditionalformatting.cpp, QXlsx/source/xlsxcontenttypes.cpp, QXlsx/source/xlsxdatavalidation.cpp, QXlsx/source/xlsxdocument.cpp, QXlsx/source/xlsxdrawinganchor.cpp, QXlsx/source/xlsxrelationships.cpp, QXlsx/source/xlsxrichstring.cpp, QXlsx/source/xlsxstyles.cpp, QXlsx/source/xlsxutility.cpp, QXlsx/source/xlsxworkbook.cpp, QXlsx/source/xlsxworksheet.cpp, TestEnv.md
Thanks for your great work!. 
We are still using Qt 4.8.7 so we had to port your library back to this old version. In Qt 4 there is not QStringLiteral class. Our replacement is QLatin1String when possible or QString as alternative if ```arg()``` was used.
Feel free to accept this request if you like.
=> Port back to qt4.8.7

QXlsx/source/xlsxworksheet.cpp
To be able to scale image in document use QImage dotsPerMeterX and dotsPerMeterY. Default qt dotsPerMeterX is 3780,
so new behavior will match previous. But can be changed setting different dotsPerMeterX and dotsPerMeterY.
=> Use QImage dotsPerMeter in insertImage.

QXlsx/QXlsx.pri, QXlsx/QXlsx.pro, QXlsx/source/xlsxcellreference.cpp, QXlsx/source/xlsxdatavalidation.cpp, QXlsx/source/xlsxdocpropsapp.cpp, QXlsx/source/xlsxdocpropscore.cpp, QXlsx/source/xlsxstyles.cpp
QXlsx not support multithread task before, e.g.:
1. Create multiple threads
2. In each thread, create a individual `QXlsx::Document` object
3. Write data to `QXlsx::Document` object
4. Save `QXlsx::Document` object to .xlsx file
The program crashed at step 4, because QXlsx use some static variables internally, which are not thread safe:
1. Some are constant dictionaries like `static QMap<DataValidation::ValidationType, QString> typeMap`, which is safe to read concurrently, but their initialization are not thread-safe.
2. Some are caches like `static QMap<int, QString> col_cache`, which should be independent from each `QXlsx::Document` object but infact is not.
I've done some tiny refactor to solve this problem:
1. For this case, initialize them with C++11 initializer-list, which is …
=> feat: support multithread tasks

CMakeLists.txt, QXlsx/header/xlsxchart_p.h, QXlsx/header/xlsxdocpropsapp_p.h, QXlsx/source/xlsxcell.cpp, QXlsx/source/xlsxchart.cpp, QXlsx/source/xlsxchartsheet.cpp, QXlsx/source/xlsxconditionalformatting.cpp, QXlsx/source/xlsxcontenttypes.cpp, QXlsx/source/xlsxdatavalidation.cpp, QXlsx/source/xlsxdocpropsapp.cpp, QXlsx/source/xlsxdocument.cpp, QXlsx/source/xlsxdrawing.cpp, QXlsx/source/xlsxdrawinganchor.cpp, QXlsx/source/xlsxrelationships.cpp, QXlsx/source/xlsxrichstring.cpp, QXlsx/source/xlsxsharedstrings.cpp, QXlsx/source/xlsxstyles.cpp, QXlsx/source/xlsxutility.cpp, QXlsx/source/xlsxworkbook.cpp, QXlsx/source/xlsxworksheet.cpp, QXlsx/source/xlsxzipreader.cpp
This disable CMake for checking for a C compiler.
Doesn't quietly fails if Qt is not found.
Add strict definitions for correct usage of
QStrings and disables the deprecated foreach
loops and other deprecated usage of Qt classes.
=> Strict fixes

CMakeLists.txt, QXlsx/header/xlsxchart_p.h, QXlsx/header/xlsxdocpropsapp_p.h, QXlsx/source/xlsxcell.cpp, QXlsx/source/xlsxcellreference.cpp, QXlsx/source/xlsxchart.cpp, QXlsx/source/xlsxchartsheet.cpp, QXlsx/source/xlsxconditionalformatting.cpp, QXlsx/source/xlsxcontenttypes.cpp, QXlsx/source/xlsxdatavalidation.cpp, QXlsx/source/xlsxdocpropsapp.cpp, QXlsx/source/xlsxdocpropscore.cpp, QXlsx/source/xlsxdocument.cpp, QXlsx/source/xlsxdrawing.cpp, QXlsx/source/xlsxdrawinganchor.cpp, QXlsx/source/xlsxformat.cpp, QXlsx/source/xlsxrelationships.cpp, QXlsx/source/xlsxrichstring.cpp, QXlsx/source/xlsxsharedstrings.cpp, QXlsx/source/xlsxstyles.cpp, QXlsx/source/xlsxutility.cpp, QXlsx/source/xlsxworkbook.cpp, QXlsx/source/xlsxworksheet.cpp, QXlsx/source/xlsxzipreader.cpp
Using contains(foo) && .value(foo) results
in two lookups on the containers using
iterators with find() and it.value() is more efficient
=> Optimize lookups

CMakeLists.txt
Use `${PROJECT_*_DIR}`, which is relative to the current `project()` instead
of `${CMAKE_*_DIR}` which is relative to the top-level CMakeLists.txt
This allows you to use the QXlsx library in another cmake based project as follows:
your_project/
third-party/QXlsx/
CMakeLists.txt
...
CMakeLists.txt:
```
add_subdirectory("third-party/QXlsx")
target_link_libraries(${PROJECT_NAME}
....
QXlsx
)
target_include_directories(${PROJECT_NAME}
PRIVATE
...
QXlsx
)
```
=> Allow library to be used with add_subdirectory() in cmake.

QXlsx/source/xlsxchart.cpp, QXlsx/source/xlsxcolor.cpp, QXlsx/source/xlsxdocpropscore.cpp, QXlsx/source/xlsxrichstring.cpp, QXlsx/source/xlsxstyles.cpp, QXlsx/source/xlsxutility.cpp, QXlsx/source/xlsxworkbook.cpp, QXlsx/source/xlsxworksheet.cpp, QXlsx/source/xlsxzipreader.cpp
- eliminates QT_VERSION macros used to hardcode QString or QStringRef
- assures lvalue
- enables compiler optimization
- assures maintainer rvalue unneeded
- insures no temporaries
- make an rvalue instance
- then make an lvalue instance
- then op=(rhs)
- auto keyword is C++11 and used elsewhere in codebase
=> QT 6 refactor - prefer const auto& reference to macros and hard coded types

CMakeLists.txt
We use QXSLX as dlls on windows and *.so on Debian - for last 3 years.
Cmake will export all the C++ functions/classes for a  dll with one line
[KDAB - Create dlls on Windows without declspec() using new CMake export all feature - July 24, 2015](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/)
To match Windows, Linux GNU can require all function references be resolved at link time
This commit supports building shared/static via cmake var
Resolves Issue 
Dynamic library #79
QXlsx as a DLL #49
=> support shared and static libraries

CMakeLists.txt
modern cmake - prefer AUTOMOC target property to global setting
=> modern cmake - prefer AUTOMOC target property to global setting

QXlsx/source/xlsxrelationships.cpp, QXlsx/source/xlsxworkbook.cpp, QXlsx/source/xlsxworksheet.cpp
Some damn xlsx files in sheet xml files don't have r attr in c tag to 
get cell position on sheet, therefore i defined rowSum columnSum to 
count rows and columns manually according to their order in the sheet 
file. I know they may not be in the right order, but there isn't other 
way and Excel and libreoffice calc and others read these files in this 
way.
In addition in this type of xlsx files some paths in relation files 
isn't normal and the path contains full address that starts with '/' 
like /xl/workbook.xml that the zip reader can't find the file, i added 
some lines to remove the extra '/' from the beginning of path if exists. 
or some paths containt '/xl' in relations file and after parsing 
relations, become with '/xl/xl/' begining. like 
'xl/worksheets/sheet.xml' => …
=> Fix issue #164

.gitignore, QXlsx/source/xlsxcellformula.cpp, QXlsx/source/xlsxchart.cpp, QXlsx/source/xlsxcolor.cpp, QXlsx/source/xlsxconditionalformatting.cpp, QXlsx/source/xlsxdrawinganchor.cpp, QXlsx/source/xlsxsharedstrings.cpp, QXlsx/source/xlsxstyles.cpp, QXlsx/source/xlsxworkbook.cpp, QXlsx/source/xlsxworksheet.cpp
Use the `QStringRef::toInt() / QStringRef::toDouble()` methods directly
=> Prevent unecessary temporary QString creations

QXlsx/header/xlsxcell.h, QXlsx/source/xlsxcell.cpp, QXlsx/source/xlsxworksheet.cpp
A static method can do the same thing without creating anything
=> Prevent unecessary Cell object creations

QXlsx/source/xlsxworksheet.cpp
Checking to see if the value to write is a double then not writing it as a double is incorrect and doesn't even match the comment directly above the incorrect code.
=> Fix StringsToNumbersEnabled not working

QXlsx/source/xlsxutility.cpp
modf of double often returns float of 0.0, so then return QDate except of QDateTime
=> Fix datetimeFromNumber() issue with std::modf float/double

QXlsx/source/xlsxworkbook.cpp
Since ST_DialogSheet and ST_MacroSheet are not yet supported;
If ST_DialogSheet or ST_MacroSheet is created in Release mode, it will fail, and if Q_ASSERT fails in Release mode, it will cause sheetNames to add an uncreated sheetName;
=> fix:Fix the residual problem after sheet creation fails

QXlsx/CMakeLists.txt
It breaks users who use "signals" keyword and convert const char* to
QString.
=> Don't force Qt definitions onto users

QXlsx/CMakeLists.txt
Strict iterators can't be used on Windows, they lead to a link error when application code iterates over a QVector<QPoint> for instance, unless Qt itself was also built with strict iterators.
See example at https://bugreports.qt.io/browse/AUTOSUITE-946
FIXES: #235
=> Disable strict iterators on Windows builds

QXlsx/CMakeLists.txt, QXlsx/header/xlsxcellrange.h, QXlsx/header/xlsxcellreference.h, QXlsx/header/xlsxstyles_p.h, QXlsx/header/xlsxutility_p.h, QXlsx/header/xlsxworksheet_p.h, QXlsx/header/xlsxzipreader_p.h, QXlsx/source/xlsxcellrange.cpp, QXlsx/source/xlsxcellreference.cpp, QXlsx/source/xlsxcolor.cpp, QXlsx/source/xlsxconditionalformatting.cpp, QXlsx/source/xlsxdatavalidation.cpp, QXlsx/source/xlsxstyles.cpp, QXlsx/source/xlsxutility.cpp
QXlsx can't even be compiled for Qt4 and
there where still some Qt4 leftovers.
This adds basic QStringView usage where it
makes sense.
=> Drop Qt5.9 and older support

.github/workflows/cmake.yml
Qt5 open source only supports x86_64 builds
on macOS, this makes sure we build for the
available archtecture.
=> Fix GitHub CI as it now uses AppleSilicon HW

QXlsx/header/xlsxcellreference.h, QXlsx/header/xlsxworksheet_p.h, QXlsx/source/xlsxcellreference.cpp, QXlsx/source/xlsxworksheet.cpp
QMap is too slow to use as storage for cells, with QHash I was able cut writeBool() & friends time by half.
=> Create a CellTable class that stores cells with QHash

QXlsx/source/xlsxutility.cpp
Switching from Qt 5.15.2 to Qt6.5.1 on Windows platform introduces HUGE performance regression in parsing of date fields when opening the XLSX files. On my laptop (i7-10510U, 32 GB RAM, Windows 10 Pro) opening of 2 MB file takes roughly 3 sec on Qt 5.15.2 and more than 3 minutes (!) on Qt 6.5.1.
The change seems to be related to some underlying changes in QDateTime class implementation - specifically performance of copy constructors seems to have degraded a lot in Qt6.
I was able to solve the problem by switching implementation of datetimeFromNumber() to new QDateTime::fromMSecsSinceEpoch() function introduced in Qt6.5.
=> fix QDateTime performance on Qt6

QXlsx/header/xlsxcellreference.h, QXlsx/source/xlsxworksheet.cpp
=> Remove undefined CellReference::fromString
